### PR TITLE
Adding Error Correction Zoo

### PR DESCRIPTION
**Pull request by valbert4**

### CODE REVIEW

**Comment by roed314** [comment]
Thanks for the contribution!  I'm quite busy this week, but will try to review it ASAP (if nobody else gets to it first).

**Comment by valbert4** [comment]
Thanks. Hopefully this can get in soon!

**Comment by roed314** [comment]
Thanks for the reminder.  I'll take a look today.

**Comment by roed314** [comment]
Thanks @katjabercic, and I'm sorry to let this sit so long @valbert4.  I've been really swamped for the past few months.

**Pull request merged**
